# Theme
import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[shell]
program = "/opt/homebrew/bin/bash"

[font]
size = 12

#[font.normal]
#family = "UbuntuNerdFont-Regular"

#[window]
#decorations = "none"

[window.padding]
x = 7
y = 7
