# Theme
import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[shell]
program = "/opt/homebrew/bin/bash"

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"

#[window]
#decorations = "none"

[window.padding]
x = 7
y = 7
