# Theme
import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[shell]
program = "/opt/homebrew/bin/bash"

[font]
size = 24

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 24
y = 24
